// components/ComingSoon.vue
<template>
  <div
    class="
      min-h-screen min-w-screen
      h-screen
      flex
      items-center
      justify-center
      bg-light-300
    "
    style="
      background-image: url('https://www.transparenttextures.com/patterns/light-wool.png');
    "
  >
    <div class="text-xl font-bold text-dark-800 p-4">We are coming soon...</div>
  </div>
</template>

// components/sections/ComingSoon.jsx
import SectionContainer from "../SectionContainer";

export default function ComingSoon() {
  return (
    <SectionContainer padding="2xl">
      <main className="flex-grow flex flex-row items-center justify-center">
        <div className="font-mono font-medium text-dark-700 text-lg">
          We Are Coming Soon!
        </div>
      </main>
    </SectionContainer>
  );
}
